"""
ABHIMANYU X - Software Bill of Materials

Real SBOM for THIS project's own Python dependencies, generated by
actually running `pip-audit` against requirements.txt — not a fabricated
package/vulnerability count. Scope is intentionally narrow: this covers
abhimanyux's own dependency tree, not the demo C targets (which have none)
and not a general-purpose scanner for arbitrary uploaded projects.
"""

import re
import subprocess
import json as _json
from pathlib import Path
from typing import Dict

REPO_ROOT = Path(__file__).resolve().parent.parent
REQUIREMENTS = REPO_ROOT / "requirements.txt"


def _direct_package_names() -> set:
    if not REQUIREMENTS.exists():
        return set()
    names = set()
    for line in REQUIREMENTS.read_text().splitlines():
        line = line.strip()
        if not line or line.startswith("#"):
            continue
        m = re.match(r"^([A-Za-z0-9_.\-]+)", line)
        if m:
            names.add(m.group(1).lower())
    return names


def generate_sbom(timeout: int = 45) -> Dict:
    """Actually runs pip-audit against requirements.txt. Returns real
    package/version/vulnerability data, or an honest error if pip-audit
    isn't available or the scan fails — never a guessed count."""
    if not REQUIREMENTS.exists():
        return {"evidence_type": "measured", "available": False,
                "error": "requirements.txt not found"}

    try:
        result = subprocess.run(
            ["pip-audit", "-r", str(REQUIREMENTS), "--format", "json"],
            capture_output=True, text=True, timeout=timeout,
        )
    except FileNotFoundError:
        return {"evidence_type": "measured", "available": False,
                "error": "pip-audit not installed — SBOM/CVE scan not run"}
    except subprocess.TimeoutExpired:
        return {"evidence_type": "measured", "available": False,
                "error": f"pip-audit did not complete within {timeout}s"}

    try:
        data = _json.loads(result.stdout)
    except Exception:
        return {"evidence_type": "measured", "available": False,
                "error": "pip-audit produced unparseable output",
                "raw_stderr": (result.stderr or "")[:500]}

    deps = data.get("dependencies", [])
    direct_names = _direct_package_names()
    direct = [d for d in deps if d["name"].lower() in direct_names]
    transitive = [d for d in deps if d["name"].lower() not in direct_names]
    vuln_packages = [d for d in deps if d.get("vulns")]

    return {
        "evidence_type": "measured",
        "available": True,
        "scanned_at": None,  # filled by caller with a real timestamp
        "total_packages": len(deps),
        "direct_count": len(direct),
        "transitive_count": len(transitive),
        "packages_with_known_issues": len(vuln_packages),
        "vulnerabilities": [
            {"package": d["name"], "version": d["version"],
             "advisories": [v.get("id") for v in d.get("vulns", [])]}
            for d in vuln_packages
        ],
        "direct_dependencies": [{"name": d["name"], "version": d["version"]} for d in direct],
        "scope_note": "Covers this project's own Python dependency tree only — "
                       "not the C demo targets (no dependencies) and not a general "
                       "scanner for arbitrary uploaded projects.",
    }
